name: practice the yaml
on: 
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install Cowsay Program
      run: sudo apt-get install -y cowsay
    - name: Create Dragon Message
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAMR" >> dragon.txt
    - name: Test File Exists
      run: grep -i "dragon" dragon.txt
    - name: Read File
      run: cat dragon.txt

      
    
 
 
  


